name: Deploy to Production

on:
  push:
    branches:
      - prod  # Trigger the workflow when changes are pushed to the 'prod' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH access
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Pull the latest changes on the server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no your_user@your_server_ip << 'EOF'
          cd /home/ignacio/airflow
          git pull origin prod
          EOF
