name: SSH Pull on Prod Push

on:
  push:
    branches:
      - prod  # Trigger action on push to 'prod' branch

jobs:
  ssh-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}  # Remote host IP or domain
          username: ${{ secrets.SSH_USER }}  # Remote SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key (must be added in GitHub secrets)
          port: 22  # Default SSH port, can be changed if needed
          script: |
            cd /path/to/your/project  # Change to your project directory on the server
            git pull origin prod  # Perform a `git pull` from 'prod' branch

