name: SSH Pull on Prod Push

on:
  push:
    branches:
      - prod  # Trigger action on push to 'prod' branch

jobs:
  ssh-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}  # Remote host IP or domain
          username: ${{ secrets.SSH_USER }}  # Remote SSH username
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key (must be added in GitHub secrets)
          port: 22  # Default SSH port, can be changed if needed
          script: |
            cd /home/ignacio/airflow/market-predictor
            git fetch origin
            git reset --hard origin/prod
            git pull origin prod

      - name: Reload requirements.txt
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}  # Remote host IP or domain
          username: ${{ secrets.SSH_USER }}  # Remote SSH username
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key (must be added in GitHub secrets)
          port: 22  # Default SSH port, can be changed if needed
          script: |
            cd /home/ignacio/airflow/market-predictor
            pip install -r requirements.txt

